import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [randomJoke, setRandomJoke] = useState(null);
  const [reload, setReload] = useState(false);
  useEffect(() => {
    async function fetchData() {
      const response = await fetch("https://api.chucknorris.io/jokes/random");
      if (response.ok) {
        const data = await response.json();
        setRandomJoke(data);
      } else {
        throw new Error(`Something went wrong...`);
      }
    }
    fetchData();
  }, [reload]);
  return (
    <>
      <Head>
        <title>Chuck Norris App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Footer />
      <main className="flex flex-col max-w-5xl m-auto">
        <section className="flex m-4 justify-between items-center">
          <img className="w-1/2" src="/img/chuck.png"></img>
          <p className="m-4">{randomJoke?.value}</p>
        </section>

        <button
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full m-auto"
          onClick={() => setReload(!reload)}
        >
          New One!
        </button>
      </main>
    </>
  );
}
