import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [randomJoke, setRandomJoke] = useState(null);
  const [reload, setReload] = useState(false);
  const [viewCount, SetViewCount] = useState(0);

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await fetch(
          "https://api.chucknorris.io/jokes/random?category=dev"
        );
        if (response.ok) {
          const data = await response.json();
          setRandomJoke(data);
        } else {
          throw new Error(`Something went wrong...`);
        }
      } catch (error) {
        alert(error.message);
      }
    }
    fetchData();
  }, [reload]);

  useEffect(() => {
    async function increaseViewCount() {
      const response = await fetch("/api/viewcount", { method: "POST" });
      if (response.ok) {
        const object = await response.json();
        SetViewCount(object.count);
      }
    }
    increaseViewCount();
  }, []);

  return (
    <>
      <Head>
        <title>Chuck Norris App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="flex flex-col max-w-5xl m-auto items-center">
        <section className="bg-sky-700 w-4/5 flex m-4 justify-between items-center shadow-xl rounded-lg">
          <img className="m-4 w-1/2" src="/img/chuck.png"></img>
          <p className="m-4 text-xl italic font-sans text-slate-100">
            {`"${randomJoke?.value}"`}
          </p>
        </section>

        <button
          className="bg-sky-700 hover:bg-sky-900 shadow-xl text-slate-100 font-bold py-2 px-4 border border-slate-100 rounded m-auto my-4"
          onClick={() => setReload(!reload)}
        >
          New One!
        </button>
      </main>
      <Footer viewCount={viewCount} />
    </>
  );
}
